# Generated by Django 3.0.8 on 2021-06-18 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lounge_booker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_guests',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='lounge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='lounge_booker.Lounge'),
        ),
    ]
