# Generated by Django 3.0.8 on 2021-06-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lounge_booker', '0002_auto_20210618_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='max_guest',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='min_guest',
            field=models.IntegerField(null=True),
        ),
    ]
