# Generated by Django 3.0.8 on 2021-06-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lounge_booker', '0003_auto_20210619_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='max_guest',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='setting',
            name='min_guest',
            field=models.IntegerField(),
        ),
    ]
