# Generated by Django 3.0.8 on 2021-06-19 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lounge_booker', '0006_auto_20210619_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='lounge',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='setting', to='lounge_booker.Lounge'),
        ),
    ]
